### ISSUE TITLE
Exception while storing riddle attempt.

### ISSUE THREAD

**Issue by juacas** [juacas/moodle-mod_treasurehunt#11]
Field 'accum_time' doesn't have a default value↵INSERT INTO mdl_scavengerhunt_attempts (road_id, riddle_id, timecreated, group_id, user_id, success, locations) VALUES ((?),(?),(?),(?),(?),(?),ST_GeomFromText((?)))↵[array (↵  0 => '1',↵  1 => '1',↵  2 => 1460477723,↵  3 => 0,↵  4 => '13',↵  5 => 1,↵  6 => 'POINT(-4.7056889533997 41.662003934037)',↵)]
↵Error code: dmlwriteexception"
errorcode
file "D:\desarrollo\apacheMoodle\moodle2\mod\scavengerhunt\externallib.php" Line 432

This happened in a local server upgraded by upgrade.php

**Comment by huorwhisp** [comment]
Solved
