### ISSUE TITLE
Incorrect sql queries for mssql server

### ISSUE THREAD

**Issue by asanufriev** [juacas/moodle-mod_treasurehunt#18]
Treasurehunt plugin doesn't work using mssql server. Many queries that use 'group by' statement are incorrect (see locallib.php):
Example:
	//incorrect variant
    $query = "SELECT r.id as roadid,count(r.id) as groupsnumber, "
            . "gm.groupid,r.validated FROM {treasurehunt_roads} r "
            . "INNER JOIN  $cond WHERE gm.userid =? AND "
            . "r.treasurehuntid=? group by roadid,gm.groupid";
	//correct variant
	$query = "SELECT r.id as roadid,count(r.id) as groupsnumber, "
            . "gm.groupid,r.validated FROM {treasurehunt_roads} r "
            . "INNER JOIN  $cond WHERE gm.userid =? AND "
            . "r.treasurehuntid=? group by r.id,gm.groupid,r.validated";//group by roadid,gm.groupid
			

Causes of errors:
1. Using 'group by' statement on field association.
2. Using 'group by' statement without aggregate function:
	$attemptsquery = "SELECT a.id,$user as user,r.position,a.timecreated, CASE WHEN EXISTS(SELECT 1 FROM "
            . "{treasurehunt_stages} ri INNER JOIN {treasurehunt_attempts} at "
            . "ON at.stageid=ri.id WHERE ri.position=r.position AND ri.roadid=r.roadid "
            . "AND $groupidwithin AND at.penalty=1) THEN 1 ELSE 0 end as withfailures, "
            . "CASE WHEN EXISTS(SELECT 1 FROM {treasurehunt_stages} ri INNER JOIN "
            . "{treasurehunt_attempts} at ON at.stageid=ri.id WHERE ri.position=r.position "
            . "AND ri.roadid=r.roadid AND $groupidwithin AND at.success=1 AND "
            . "at.type='location') THEN 1 ELSE 0 end as success FROM {treasurehunt_attempts} a INNER JOIN "
            . "{treasurehunt_stages} r ON a.stageid=r.id INNER JOIN {treasurehunt_roads} "
            . "ro ON r.roadid=ro.id WHERE ro.treasurehuntid=? AND $groupid group by r.position,user,a.id,r.roadid";	//what does that 'group by' mean? may be 'order by'?
3. Using reserved words:
	$sql = <<<SQL
        SELECT $user as user,$grademethodsql(SELECT COUNT(*) from 		--please use: SELECT $user as 'user',...
        {treasurehunt_attempts} at INNER JOIN {treasurehunt_stages} ri
        ON ri.id = at.stageid INNER JOIN {treasurehunt_roads} roa ON
        ri.roadid=roa.id where roa.treasurehuntid=ro.treasurehuntid AND
        at.type='location' AND at.penalty=1 AND $groupidwithin) as
        nolocationsfailed,
        (SELECT COUNT(*) from {treasurehunt_attempts} at INNER JOIN
        {treasurehunt_stages} ri ON ri.id = at.stageid INNER JOIN
        {treasurehunt_roads} roa ON ri.roadid=roa.id where
        roa.treasurehuntid=ro.treasurehuntid AND at.type='question' AND
        at.penalty=1 AND $groupidwithin) as noanswersfailed,
        (SELECT COUNT(*) from {treasurehunt_attempts} at INNER JOIN
        {treasurehunt_stages} ri ON ri.id = at.stageid INNER JOIN
        {treasurehunt_roads} roa ON ri.roadid=roa.id where
        roa.treasurehuntid=ro.treasurehuntid AND at.type='location'
        AND at.success=1 AND $groupidwithin) as nosuccessfulstages,
        (SELECT COUNT(*) from {treasurehunt_stages} ri INNER JOIN
        {treasurehunt_roads} roa ON ri.roadid=roa.id where
        roa.treasurehuntid=ro.treasurehuntid AND roa.id=ro.id) as nostages
        from $usertimetable {treasurehunt_attempts} a INNER JOIN {treasurehunt_stages}
        r ON r.id=a.stageid INNER JOIN {treasurehunt_roads} ro ON
        r.roadid=ro.id $groupsmembers WHERE ro.treasurehuntid=?  AND a.userid IN $users
        AND $groupid group by $user,ro.treasurehuntid,a.groupid,ro.id $orderby
SQL;

**Comment by juacas** [comment]
There is a tentative fix in commit 2e56a89080cdf046f4f9b4dc31b31567383a88ff
Maybe you can checkout this version and check if it works well with MSSQL .
Thank you very much for your advice and suggestions.

**Comment by asanufriev** [comment]
//locallib.php -  981 line
$query = "SELECT a.id as id,a.timecreated,a.userid as 'user',a.stageid,CASE WHEN a.success = 0 "
            . "THEN NULL ELSE r.name END AS name, CASE WHEN a.success=0 THEN NULL ELSE "
            . "r.cluetext END AS cluetext,a.geometrysolved,r.position,a.location as geometry,"
            . "r.roadid,r.id AS stageid,a.success FROM (SELECT MAX(at.id) AS id,"
            . "at.location AS geometry FROM {treasurehunt_attempts} "
            . "at INNER JOIN {treasurehunt_stages} ri ON ri.id=at.stageid WHERE ri.roadid=? "
            . "AND $grouptypewithin order by at.stageid, geometry) apt INNER JOIN {treasurehunt_attempts} a ON "
            . "a.id = apt.id INNER JOIN {treasurehunt_stages} r ON a.stageid=r.id WHERE "
            . "r.roadid=? AND $grouptype";
//it's wrong query, because it contains "MAX" aggregation function

//try this
$query = "SELECT a.id as id,a.timecreated,a.userid as 'user',a.stageid,CASE WHEN a.success = 0 "
            . "THEN NULL ELSE r.name END AS name, CASE WHEN a.success=0 THEN NULL ELSE "
            . "r.cluetext END AS cluetext,a.geometrysolved,r.position,a.location as geometry,"
            . "r.roadid,r.id AS stageid,a.success FROM (SELECT MAX(at.id) AS id,"
            . "at.location AS geometry FROM {treasurehunt_attempts} "
            . "at INNER JOIN {treasurehunt_stages} ri ON ri.id=at.stageid WHERE ri.roadid=? "
            . "AND $grouptypewithin group by at.stageid, at.location) apt INNER JOIN {treasurehunt_attempts} a ON "
            . "a.id = apt.id INNER JOIN {treasurehunt_stages} r ON a.stageid=r.id WHERE "
            . "r.roadid=? AND $grouptype";

**Comment by asanufriev** [comment]
//locallib.php -  981 line
$query = "SELECT a.id as id,a.timecreated,a.userid as 'user',a.stageid,CASE WHEN a.success = 0 "
            . "THEN NULL ELSE r.name END AS name, CASE WHEN a.success=0 THEN NULL ELSE "
            . "r.cluetext END AS cluetext,a.geometrysolved,r.position,a.location as geometry,"
            . "r.roadid,r.id AS stageid,a.success FROM (SELECT MAX(at.id) AS id,"
            . "at.location AS geometry FROM {treasurehunt_attempts} "
            . "at INNER JOIN {treasurehunt_stages} ri ON ri.id=at.stageid WHERE ri.roadid=? "
            . "AND $grouptypewithin order by at.stageid, geometry) apt INNER JOIN {treasurehunt_attempts} a ON "
            . "a.id = apt.id INNER JOIN {treasurehunt_stages} r ON a.stageid=r.id WHERE "
            . "r.roadid=? AND $grouptype";
//it's wrong query, because its subquery contains "MAX" aggregation function

//try this
$query = "SELECT a.id as id,a.timecreated,a.userid as 'user',a.stageid,CASE WHEN a.success = 0 "
            . "THEN NULL ELSE r.name END AS name, CASE WHEN a.success=0 THEN NULL ELSE "
            . "r.cluetext END AS cluetext,a.geometrysolved,r.position,a.location as geometry,"
            . "r.roadid,r.id AS stageid,a.success FROM (SELECT MAX(at.id) AS id,"
            . "at.location AS geometry FROM {treasurehunt_attempts} "
            . "at INNER JOIN {treasurehunt_stages} ri ON ri.id=at.stageid WHERE ri.roadid=? "
            . "AND $grouptypewithin group by at.stageid, at.location) apt INNER JOIN {treasurehunt_attempts} a ON "
            . "a.id = apt.id INNER JOIN {treasurehunt_stages} r ON a.stageid=r.id WHERE "
            . "r.roadid=? AND $grouptype";

**Comment by juacas** [comment]
The proposed query is not functionally equivalent to the previous query.
Is the following query conformant with MSSQL?

```
$query = "SELECT a.id as id,a.timecreated,a.userid as 'user',a.stageid,CASE WHEN a.success = 0 "
            . "THEN NULL ELSE r.name END AS name, CASE WHEN a.success=0 THEN NULL ELSE "
            . "r.cluetext END AS cluetext,a.geometrysolved,r.position,a.location as geometry,"
            . "r.roadid,r.id AS stageid,a.success FROM ("
            . "SELECT MAX(at.id) AS id FROM {treasurehunt_attempts} at "
            . "INNER JOIN {treasurehunt_stages} ri ON ri.id=at.stageid WHERE ri.roadid=? "
            . "AND $grouptypewithin) apt "
            . "INNER JOIN {treasurehunt_attempts} a ON "
            . "a.id = apt.id INNER JOIN {treasurehunt_stages} r ON a.stageid=r.id WHERE "
            . "r.roadid=? AND $grouptype";
```

**Comment by juacas** [comment]
Thanks, testing...

**Comment by asanufriev** [comment]
it's correct query

2017-10-31 12:14 GMT+03:00 Juan Pablo de Castro <notifications@github.com>:

**Comment by juacas** [comment]
Sorry, your query is the correct. I sent the previous message too loosely.  Your query is committed in develop branch. Everything is running ok in my tests.

**Comment by asanufriev** [comment]
Query fix is not included in the new version 1.2.6:
//locallib.php - 1036 line
$query = "SELECT a.id as id,a.timecreated,a.userid as 'user',a.stageid,CASE WHEN a.success = 0 "
            . "THEN NULL ELSE r.name END AS name, CASE WHEN a.success=0 THEN NULL ELSE "
            . "r.cluetext END AS cluetext,a.geometrysolved,r.position,a.location as geometry,"
            . "r.roadid,r.id AS stageid,a.success FROM ("
            . "SELECT MAX(at.id) AS id,"
            . "at.location AS geometry FROM {treasurehunt_attempts} at "
            . "INNER JOIN {treasurehunt_stages} ri ON ri.id=at.stageid WHERE ri.roadid=? "
            . "AND $grouptypewithin group by at.stageid, geometry) apt "
            . "INNER JOIN {treasurehunt_attempts} a ON "
            . "a.id = apt.id INNER JOIN {treasurehunt_stages} r ON a.stageid=r.id WHERE "
            . "r.roadid=? AND $grouptype";

**Comment by juacas** [comment]
v1.2.7 includes your query.
Please report if the module is fully compatible with MSSQL.
Thanks for your assistance and your patience.

**Comment by juacas** [comment]
you are welcome
