### ISSUE TITLE
locked buttons in firefox (v.1.2.7)

### ISSUE THREAD

**Issue by asanufriev** [juacas/moodle-mod_treasurehunt#20]
/mod/treasurehunt/edit.php

![image](https://user-images.githubusercontent.com/12484317/32482328-4656c304-c3a8-11e7-9062-2896f7bf731a.png)

**Comment by juacas** [comment]
Can't reproduce here with Moodle 3.2 and  Firefox 57.
Please provide more info:
* Moodle version.
* Firefox version.
* Javascript console (if errors are present).
* Does the locking remains when after reloading the page?
* Can you reproduce this behaviour consistently? That is, can you describe a sequence of steps that leads to the locking?
* Does the locking occurs with Chrome?

**Comment by asanufriev** [comment]
1. $release  = '3.2.5+ (Build: 20170915)';
2. 56.0.2 (64-bit)
3. no errors
4. buttons are not locked when page is loaded first time. But after page reloading they are locked.
5. see item 4
6. with chrome all works well

**Comment by juacas** [comment]
Release v1.2.18 solves this issue.
