### ISSUE TITLE
Space after commas

### ISSUE THREAD

**Issue by dinism** [juacas/moodle-mod_treasurehunt#22]
To have this (example): dinism, juaca, me, you **NOT** dinism,juaca,me,you
![imagem](https://user-images.githubusercontent.com/14828021/35363914-68a927f4-0164-11e8-8fff-4956601e098f.png)

**Comment by juacas** [comment]
Thank you for your collaboration. The fix will be included in the next release.

**Comment by dinism** [comment]
In test using develop edition when you edit road i got this

Fields list in snapshot record does not match fields list in 'treasurehunt_roads'. Record is missing fields: treasurehuntid, timecreated, timemodified, groupingid, validated
line 906 of /lib/classes/event/base.php: call to debugging()
line 2179 of /mod/treasurehunt/locallib.php: call to core\event\base->add_record_snapshot()
line 109 of /mod/treasurehunt/editroad.php: call to treasurehunt_add_update_road()
