### ISSUE TITLE
General exception message

### ISSUE THREAD

**Issue by aguatacuperche** [juacas/moodle-mod_treasurehunt#24]
Hi. I have this message that appears just when the activity is saved (Moodle version 3.5+)

Excepción - Argument 1 passed to file_get_all_files_in_draftarea() must be of the type integer, null given, called in [dirroot]/lib/form/filemanager.php on line 336

Debug info: 
Error code: generalexceptionmessage

Stack trace:
line 767 of /lib/filelib.php: TypeError thrown
line 336 of /lib/form/filemanager.php: call to file_get_all_files_in_draftarea()
line 580 of /lib/formslib.php: call to MoodleQuickForm_filemanager->validateSubmitValue()
line 526 of /lib/formslib.php: call to moodleform->validate_defined_fields()
line 636 of /lib/formslib.php: call to moodleform->is_validated()
line 1096 of /course/moodleform_mod.php: call to moodleform->get_data()
line 313 of /mod/treasurehunt/mod_form.php: call to moodleform_mod->get_data()
line 150 of /course/modedit.php: call to mod_treasurehunt_mod_form->get_data()

Best regards

**Comment by juacas** [comment]
Hi,
please, can you report the sequence of steps that renders that error?
I can't reproduce it with my setup.

best regards.

**Comment by aguatacuperche** [comment]
Hi,
[send you a video](https://drive.google.com/file/d/1OHrxSGoVLqqKfBJmmYTRVEWqZk6oFMgP/view?usp=sharing) (45 secs) with the sequence of steps.

Best regards.

**Comment by aguatacuperche** [comment]
Hi juacas I have updated to version 1.2.19 and the problem has been solved. Moodle does not return errors in the "developer mode".

![resuelto](https://user-images.githubusercontent.com/41389348/43454539-4efe67c6-94b5-11e8-9199-7c4b33ff8978.png)

I've also tried it in a 3.6 dev version of Moodle and it works fine.

Thanks

**Comment by juacas** [comment]
Thank you for your help.
Enjoy the module!
