### ISSUE TITLE
Adding this to my Moodle instance made my links work wrong.

### ISSUE THREAD

**Issue by WNYmathGuy** [juacas/moodle-mod_treasurehunt#27]
I'm in Moodle 3.8+ (Build: 20191129) right now and will be upgrading soon. I have a lot of Plugins, so it's hard to say why the problem happened. I use the BOOST theme for the main website operation. Right after installing Treasurehunt the links at the main page didn't go anywhere. The browser URL would change, but the redirect would never happen. If the Search was used, I could navigate to the appropriate page. Immediately after uninstalling Treasurehunt the buggy links were restored to normal.

I'm doing a lot of things right now, so I won't respond immediately, but I love your concept, so I want to contribute to the debugging in any way I can. I'm a hack admin though so often you'll have to tell me how to get the tech info you need to do the diagnostics.

**Comment by WNYmathGuy** [comment]
I had a bit of time to upgrade to Moodle 3.8.1+ (Build: 20200130). Adding Treasurehunt back in had the same results. Here are some screenshots showing URL's where page rendering doesn't happen.

**Here we see that I cannot use the fancy menu to get to settings or logout.**
![Screenshot from 2020-01-31 17-55-38](https://user-images.githubusercontent.com/28640985/73580526-dc774600-4453-11ea-8748-7c1c2386d7a2.png)

**Clicking the button for _Site administration_ with the wrench icon renders right, but...**
![Screenshot from 2020-01-31 17-55-50](https://user-images.githubusercontent.com/28640985/73580582-0f213e80-4454-11ea-9ea2-b4fc8f473d66.png)

**...clicking the _Plugins_ tab is ineffective, and...**
![Screenshot from 2020-01-31 17-56-09](https://user-images.githubusercontent.com/28640985/73580654-4b549f00-4454-11ea-8e77-18085a91eee6.png)

**...clicking the _Users_ tab is ineffective.**
![Screenshot from 2020-01-31 17-56-22](https://user-images.githubusercontent.com/28640985/73580688-73440280-4454-11ea-9855-8f8eb51ffa7c.png)

**Some links still work fine, like the _(Log out)_ link in the page footer is fine.**
![Screenshot from 2020-01-31 17-56-58](https://user-images.githubusercontent.com/28640985/73580748-b1d9bd00-4454-11ea-9e7a-a38a242c0708.png)

**Running a search from the _Site administration_ page for "plugins overview" gets me a working link to that area.**
![Screenshot from 2020-01-31 17-58-03](https://user-images.githubusercontent.com/28640985/73580853-244a9d00-4455-11ea-857c-d65a8b628c4b.png)

**Results are as expected**
![Screenshot from 2020-01-31 17-58-20](https://user-images.githubusercontent.com/28640985/73580918-6ecc1980-4455-11ea-840d-5c739afffa79.png)

So again after uninstalling the Treasurehunt plugin all the links and menus went back to normal.

**Comment by dinism** [comment]
I think is JavaScript issue.
Try this:
1- Adding this in config.php solves it?
$CFG->cachejs = false; 
OR
2- In  Site administration / Appearance / AJAX and Javascript 
try to uncheck the Cache Javascript

**Comment by juacas** [comment]
Indeed it is a Javascript conflict. Disabling cachejs fix it.
It may be related with some of the new babel.js compiler in Moodle 3.8 but currently I don't know the solution.

**Comment by juacas** [comment]
I found the reason and the fix of the problem: The treasurehunt player page need to use jquery2 and Babel doesn't like to compile two versions of jQuery.
Just remove jquery2.1.4.min.js from amd/src and amd/build or just update the module from the repository version v1.2.22c.

Sorry for the inconveniences.
Please, confirm the solution to close this issue.

**Comment by juacas** [comment]
After some tests this issue has been corrently diagnosed and now it is considered solved.
Thanks for reporting!

**Comment by WNYmathGuy** [comment]
I finally got a moment to read this. I moved recently and still opening boxes after the move.

Just put the plugin into my system with the web installer from the store and it works perfectly!
