### ISSUE TITLE
Add a way to view again the guided tour

### ISSUE THREAD

**Issue by patsej** [juacas/moodle-mod_treasurehunt#28]
The guided tour of the app (popups explaining the different elements of the interface) appears the first time the user opens the app.
That would be good to have a way to view it whenever we need.
A button or a link could be added in that effect.

If the tour is based on Moodle's user tour, Jon Bolton on Moodle's [forum](https://moodle.org/mod/forum/discuss.php?d=396434#p1598778) gave this tip:
"If the tour is enabled, this code can be put in a block or anywhere else you can add text. I use it in a block to make the tour reset link more obvious for the users.

```
<a href="#" data-action="tool_usertours/resetpagetour" class="btn btn-primary">Reset user tour on this page</a>
```

**Comment by juacas** [comment]
Currently there are two tours: one in the "edit stages" page and another in the "player" page (navigation map).
What could be the best UI redesign for this feature?
Being this mostly a one-use feature the action element should be very unobstrusive.

**Comment by juacas** [comment]
Please, check commit 4ffeafb47236a16acbe58e4f860e48be4f09142c for a implementation proposal.

**Comment by patsej** [comment]
Thanks for the fix of the player page!
It works well :-)

**Comment by juacas** [comment]
It will be published in the next release.
Cheers.

**Comment by patsej** [comment]
Thanks!
