### ISSUE TITLE
Students don't access the player in groupmode=0

### ISSUE THREAD

**Issue by juacas** [juacas/moodle-mod_treasurehunt#3]
A error message is thrown:
Error
Not a member of any group, so unable to make the activity.

But groupmode==false and the hunt has only one Road, hence there is no need that the students are grouped.

**Comment by huorwhisp** [comment]
Solucionado. Para ello, a la hora de encontrar el grupo y camino al que pertenece el usuario he puesto la condición de que solo me devuelva los caminos validados y que en el caso de que exista solo 1 validado y sin opción de grupo les deje participar a todos en él.No sé si es la mejor solución, porque eso conlleva que si el profesor ha hecho 3 caminos y solo está validado 1, aunque se haya molestado en separar en tres grupos y asignarlos cada uno a su camino todos jugarán por el único validado

**Comment by huorwhisp** [comment]
He cambiado lo anterior, permito recoger los caminos no validados de la base de datos para que si tienen grupo asignado pero el camino no está validado salga un error indicando que el camino aún no está terminado. De esta forma, en el caso anterior de que haya 3 caminos con sus correspondientes grupos asignados y solo haya uno validado, únicamente el grupo asignado a ese camino podrá realizar la actividad

**Comment by juacas** [comment]
Mejor así. Hay que hacer prevalecer la configuración del profesor. Si se han creado diversos caminos hay que obligar a que se asignen grupos (o groupins) a todos, y la lógica de asignación será la de los grupos (o groupings) elegidos por el profesor.
Si sólo hay un camino se puede admitir que no haya una selección de grupo (se asume un grupo con todos los alumnos), excepto que la forma de juego sea por equipos en cuyo caso es obligatorio seleccionar un "grouping" para definir los equipos.
