### ISSUE TITLE
Add a way to set the help URL

### ISSUE THREAD

**Issue by patsej** [juacas/moodle-mod_treasurehunt#30]
The help close to the name of the activity shows a link to a tutorial which has a fixed URL.
`<a href="https://juacas.github.io/moodle-mod_treasurehunt/index.html">More info and step-by-step tutorial in this online presentation.</a>`

Being able to point to a dedicated course or page adapted to the audience would help a lot.

**Comment by juacas** [comment]
Hi,
two considerations about this feature proposal:

- The page linked is the official presentation page of the module and it's intended to be useful for the average user.

- that string is located in the language packs of Moodle. For local customizations one can use "/admin/tool/customlang/index.php" section of Moodle admin and customize the string with 'editactivity_help' locally.

I'm not sure that implementing this feature will provide more value than complexity to the module.

Opinions?
