### ISSUE TITLE
Webcam permission denial leads to lost space at the top of the page

### ISSUE THREAD

**Issue by patsej** [juacas/moodle-mod_treasurehunt#31]
When there is at least 1 QRCode in a route, the app asks for permission to use the webcam.
If it is denied, a big space (where the video of the camera should be seen is lost at the top of the page.
Could it be removed?
I have the impression that it was the case before.

See here:
![image](https://user-images.githubusercontent.com/3079564/74038692-dee01f80-49c0-11ea-9b65-3e5ba83c805d.png)

**Comment by patsej** [comment]
Hey Juan-Pablo,
Is the "Improve QR scanner lib & msgs." Issue #31 the issue that introduced this new (wrong) behavior?
Would you know what should be changed to fix it?
Thx ;-)

**Comment by juacas** [comment]
Please, check develop branch. There are some fixes about the javascript libraries for QR scanner.
Can you ellaborate about the behavior you mention (if the problem persists)?
Best.

**Comment by patsej** [comment]
I've just seen that it works properly on Chrome.
But it's still showing up the white space on Firefox.

**Comment by juacas** [comment]
Fixed in branch develop. MediaObject reports different on errors. This need to be tested in Safari also, I suppose. Can you test it with Apple Mac or IPhone?

**Comment by patsej** [comment]
It's great, thanks ;-)
