### ISSUE TITLE
Improve the messages that pop up after answering a question

### ISSUE THREAD

**Issue by patsej** [juacas/moodle-mod_treasurehunt#32]
After answering a question, the message displayed in a popup is difficult to read because (too much text) 
![image](https://user-images.githubusercontent.com/3079564/74041650-582e4100-49c6-11ea-9c7c-acff4c2e9169.png)

One first idea I can think of would be to 
- put the statuses ("Successful answer" and "Stage 5 overcome") in bold
- display only the time and not the date
- replace "on date:" with "at " (without the colon)

Here is an example:
![image](https://user-images.githubusercontent.com/3079564/74042398-be679380-49c7-11ea-8ba3-91771e7ad123.png)

Are there cases where the date may be different? If yes, would it be a problem ? (would playing just before midnight fall in this case?)
The 2 statuses ("Successful answer" and "Stage 5 overcome") can be done by 2 different persons?

**Comment by juacas** [comment]
These two messages come from independent (but related) events:
* A stage can be overcome by other team member.
* A stage need to commit a set of requirements (By now: position, answer, activity completion) and the last two can occur in any order.

IMHO only the date format can be fixed.

**Comment by patsej** [comment]
Ok, thx!
If the date is different from the current one we will need to display the full info I think.
Let me know if you need some help with the date (I don't know yet where it is and how it works).
