### ISSUE TITLE
After a question, display the clue

### ISSUE THREAD

**Issue by patsej** [juacas/moodle-mod_treasurehunt#33]
After answering the question, a popup shows up to congratulate the player with a message like "Successful answer….".

Closing this popup, “nothing happens”, i.e. the player will be left on the map with no clue.

To know what to do next he has to click on the "burger" or the (I) button information to get the details for the next step. 
Could show the Clue?

**Comment by patsej** [comment]
Are there use cases against to not display the clue? Or can we safely show the menu?

**Comment by juacas** [comment]
Indeed, I agree that the "info panel" should be opened after answering the question (or after a change in the state of the stage).

**Comment by patsej** [comment]
Great! Is it easy to fix?

**Comment by juacas** [comment]
There is a fix in develop branch. You can test it.

**Comment by patsej** [comment]
I test it, thanks! 😁

**Comment by patsej** [comment]
Which commit it corresponds to? I don't see any change.

Except that new notification that contains a duplicated text
![image](https://user-images.githubusercontent.com/3079564/75067598-b3dfea80-54ed-11ea-868e-40bced1aacfd.png)

**Comment by patsej** [comment]
I've found the commit: Open Info after question Issue #32
I've checked that my code is up-to-date. 

In the console, the messages look good 
"Correct answer. first.js:134:7143
pagecontainershow first.js:233:347"
but in reality the menu does not appear after the user validates the status window.
Could you have a look please? Let me know if you need my help to test ;-)

**Comment by patsej** [comment]
I've found the commit: Open Info after question Issue #32
I've checked that my code is up-to-date. 

In the console, the messages look good 
"Correct answer. first.js:134:7143
pagecontainershow first.js:233:347"
but in reality the menu does not appear after the user validates the status window.
I've tested on my phone and I get the same behavior.

Could you have a look please? Let me know if you need my help to test ;-)

**Comment by juacas** [comment]
After each status change (answer, stage passed, etc) the interface should open the left panel with the proper UI elments (next cluer, answer button, locking activity, etc). This is what I get in all my tests.
If this is not your experience, please write down the exact sequence of actions that leads you to the problem.

**Comment by patsej** [comment]
It works very well, thanks!
