### ISSUE TITLE
White space at the bottom of the Game screen

### ISSUE THREAD

**Issue by patsej** [juacas/moodle-mod_treasurehunt#35]
A space appears now at the bottom of the Game page, above the buttons
![image](https://user-images.githubusercontent.com/3079564/74451474-f8c9a880-4e7f-11ea-8f22-381fdfaf3c99.png)

It has been introduced by the commit [Fixed style issues on the game page](https://github.com/juacas/moodle-mod_treasurehunt/commit/765dd539d122e813beb41cd32e8ac9b19e341200)

Due to box-sizing: unset !important; commented out in treasure.css
```
*,
*::before,
*::after {
   /* box-sizing: unset !important; */
}
```

Why was it necessary?

Replacing if by the following code works
```
div#mappage {
    box-sizing: unset !important;
}
```

I haven't seen any regression. Could you also check please?

**Note:** I've included this patch in the "Fix Simple question's answer layout" PR.

**Comment by juacas** [comment]
Merged into develop branch. 
Thanks!  👍

**Comment by patsej** [comment]
Great, thanks! 😁

**Comment by patsej** [comment]
I've tried to remove the !important in the definition of div#mappage. I noticed no difference.
Do you know if it is mandatory for another theme or if there is a case where it's useful?
If not, it would be better to remove it :-)

**Comment by patsej** [comment]
BTW, do you know if there is a  way to get rid of the scrollbar that appears to the right?

**Comment by juacas** [comment]
Sorry but, there is no scrollbar in any of my tests/devices.

**Comment by patsej** [comment]
That's a good news :-D It's not a problem.
It's on Firefox. On Chrome the scrollbar does not appear.
