### ISSUE TITLE
Improve layer map icon to avoid confusion

### ISSUE THREAD

**Issue by patsej** [juacas/moodle-mod_treasurehunt#36]
The icon for choosing the type of layers on the map looks like a list of steps. It is confusing.
 
![image](https://user-images.githubusercontent.com/3079564/74754292-b3d3b680-5271-11ea-8dc8-3bca981e1a9c.png)

What about using it for the steps and using the same as in the Edition screen for the layers (![layers](https://user-images.githubusercontent.com/3079564/74755033-cf8b8c80-5272-11ea-9ad7-cf50609b5522.png))?

Here is a proposal
![image](https://user-images.githubusercontent.com/3079564/74757010-b9cb9680-5275-11ea-84f2-5c5b665b0802.png)
I've grouped the Location and Layer buttons to make it clearer that they have an influence on the map.

Note that the (I) icon also appears in the menu bar if the text is too long.
![image](https://user-images.githubusercontent.com/3079564/74949380-fde9a300-53fd-11ea-85eb-ac1e26ce9e2e.png)

**Comment by juacas** [comment]
Thanks for your contributions.

IMHO it’s preferable to use a standard icon from the framework ( <https://demos.jquerymobile.com/1.4.5/icons/> https://demos.jquerymobile.com/1.4.5/icons/) but it can be customized if needed ( <https://demos.jquerymobile.com/1.4.5/icons/#CustomIcons> https://demos.jquerymobile.com/1.4.5/icons/#CustomIcons).

Please, propose a vectorial (SVG) icon aligned with the look&feel of the app.

 

Regards.

 

De: patsej <notifications@github.com> 
Enviado el: martes, 18 de febrero de 2020 17:21
Para: juacas/moodle-mod_treasurehunt <moodle-mod_treasurehunt@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Asunto: [juacas/moodle-mod_treasurehunt] Improve layer map icon to avoid confusion (#36)

 

The icon for choosing the type of layers on the map looks like a list of steps. It is confusing.

 <https://user-images.githubusercontent.com/3079564/74754292-b3d3b680-5271-11ea-8dc8-3bca981e1a9c.png> 

What about using it for the steps and using the same as in the Edition screen for the layers?
 <https://user-images.githubusercontent.com/3079564/74755033-cf8b8c80-5272-11ea-9ad7-cf50609b5522.png> 

I'm going to add a proposal when I've got more time.

**Comment by patsej** [comment]
Hey Juan-Pablo,

Thanks for your feedback. I'm checking which one would be a match ;-)
I've updated the description to add the fact that the (I) icon is also used in the menu bar if the text is too long.

**Comment by patsej** [comment]
If it's really important to choose among those icons, I would choose the eye 
![image](https://user-images.githubusercontent.com/3079564/74983457-5472d380-5436-11ea-9ac7-4d04f6ff544e.png)
or the grid
![image](https://user-images.githubusercontent.com/3079564/74983863-6bb1c100-5436-11ea-993f-28082d9e61ed.png)

I like the semantic of the eye is good. On the other hand it may be close visually to the location icon.
But I think it will be fine.
What do you think?

**Comment by patsej** [comment]
Thanks !!
