### ISSUE TITLE
Edit screen is locked for 1 user and I cannot unlock it

### ISSUE THREAD

**Issue by patsej** [juacas/moodle-mod_treasurehunt#37]
When one teacher user visited the Edit screen, another teacher cannot get access to it.

He receives the following message:

> “The user X is editing this treasurehunt right now. Try to edit it in a few minutes.
> [More information about this error](https://docs.moodle.org/34/en/error/treasurehunt/treasurehuntislocked)”

What’s more the link leads to a **page that does not exist**. 
On my version it points to https://docs.moodle.org/34/en/error/treasurehunt/treasurehuntislocked

I've tried to log out but it didn't change anything.

Is there a way for the administrator and/or the current user to unlock it?
Otherwise, how long should I wait? Is it linked to the session duration (several hours) ?
Would it be possible to add a button to leave the page?

Thx ;-)

**Comment by juacas** [comment]
It is a "feature" designed to avoid edit conflicts on a treasurehunt.
- The link is a standard of Moodle. It points to a Wiki that everybody can edit (just register at moodle.org). Unfortunally it is currently empty.
- There is no way to unlock the edition page other than waiting a predefined timeout.
- That timeout is configured system-wide in the module settings ( at admin/settings.php?section=modsettingtreasurehunt parameter **locktimeediting**).

If the lock is not renewed after **locktimeediting** seconds (i.e. the page is closed) the lock is released and other user can adquire it.

**Comment by patsej** [comment]
Thanks a lot for this explanation 👍 ;-)
