### ISSUE TITLE
The map sometimes does not appear (timeout on images tiles)

### ISSUE THREAD

**Issue by patsej** [juacas/moodle-mod_treasurehunt#38]
I've just noticed a weird  map. It was kind of empty.

The dev logs talk about CORS.
But when I tried to access one image like the following one, I got timeouts
https://c.tile.openstreetmap.org/8/137/91.png
After several reloads it finally showed the picture...

Have you ever had the same issue? Where does it come from? How can it be fixed?

**Comment by juacas** [comment]
It seems to be a QoS issue i openstreetmap. It happened to me fromtime to time and I checked that those urls fail the same way if you try to load them directly in a browser.
Please, do this test the next time and, if it is concluyent, close this issue.

**Comment by patsej** [comment]
Thanks for the answer!
