### ISSUE TITLE
JavaScript problem disables all edit functions in Moodle

### ISSUE THREAD

**Issue by ger82** [juacas/moodle-mod_treasurehunt#41]
Hello,
it is like on this [site](https://bitbucket.org/covuni/moodle-mod_bootstrapelements/issues/12/javascript-problem-disables-all-edit)

Error message: "Error: Mismatched anonymous define() module: [object Object]" require.min.js:5

if I uninstall the plugin then it works everything fine.

**Comment by juacas** [comment]
Thank you for your feedback.
It seems that it is caused by the new Moodle 3.8 javascript compressor.
I've just released version 1.3.1-hotfix with a fix.
