### ISSUE TITLE
Exception - Class 'mod_treasurehunt\model\stage' not found

### ISSUE THREAD

**Issue by konghao666** [juacas/moodle-mod_treasurehunt#43]
when i save the active , it show me :Exception - Class 'mod_treasurehunt\model\stage' not found

**Comment by juacas** [comment]
Hi, thank you for reporting.
Can you explain better the steps you did to reproduce the issue?
What is "the active"?

**Comment by metaxakis** [comment]
I have the same problem!
I installed the plugin and then I tried to create an activity in a lesson and when I saved it  got:
Exception - Class 'mod_treasurehunt\model\stage' not found

**Comment by juacas** [comment]
I've just released a hotfix version. Sorry fo the inconveniences.

**Comment by metaxakis** [comment]
Thank you for the immediate response
I installed it and now the new error is:
Error writing to database

**Comment by juacas** [comment]
Please, paste here the full error displayed in your screen.

**Comment by metaxakis** [comment]
Thanks again!
Well I uninstalled the plugin (Treasure Hunt) and I installed it again automatically from the moodle plugins directory.
After the installation finished I tried again to create an activity by filling just the required fields (only Treasure hunt's name)  and pressing "Save and return to course"
After that I get the error:
Error writing to database

More information about this error


Thanks

**Comment by juacas** [comment]
Sorry for the precipitation. Rush is not good :(

Please check the new release and report.
Thanks.

**Comment by metaxakis** [comment]
Yes I know
But you made it now!!!
It looks ok now!
I re installed and no error appeared.
I will try it because this is the first time I will use it and I will report if I found anything else 
Many thanks for everything

**Comment by konghao666** [comment]
Hi

**Comment by konghao666** [comment]
Hi juacas
the treasurehunt is a great  plugin，I like it very much，Thank you very much for your contribution，

I have been using moodle to carry out teaching activities with my students. In China, students can play outdoors and study, which is a very exciting thing for students。

today i update the plugin to the 2020032301，Returns the following information

异常 - syntax error, unexpected 'if' (T_IF), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$'

关于这个错误的更多信息

×Debug info：
Error code: generalexceptionmessage
×Stack trace：
line 116 of /mod/treasurehunt/db/upgrade.php: ParseError thrown
line 532 of /lib/upgradelib.php: call to upgrade_plugins_modules()
line 1877 of /lib/upgradelib.php: call to upgrade_plugins()
line 694 of /admin/index.php: call to upgrade_noncore()

I am very sorry that my English is poor. I used the translation software, but the translation of the software seems not so good

**Comment by juacas** [comment]
Please, update to the new v1.3.1d release. The package v1.3.1d is fixed.

**Comment by juacas** [comment]
By the way, I would be delighted to hear about your experience with the module.
