### ISSUE TITLE
Problem on Moodle mobile

### ISSUE THREAD

**Issue by DavidDelco** [juacas/moodle-mod_treasurehunt#44]
Hi everybody,
I've installed this fantastic plugin onto my Moodle (V. 3.7.3+ on private Windows Server 16). The plugin run good on the web (I didn't yet try all feature, but it run). I've tried it on the mobile app for iOS and I get an error message:  "Uh oh! Your organisation installed a plugin that is non yet supported
Contact the site administrator and tell them you want to use this activity with the Moodle Mobile app. You can still use it using your device's web browser."

Why? How can I resolve? Thank for your help

![Treasure_Haunt_Mobile_Error](https://user-images.githubusercontent.com/54086232/79972080-ad420500-8495-11ea-87e7-475c7bda70c4.jpg)

**Comment by juacas** [comment]
Just "Apri nel browser".
Moodle App supports a very small fraction of the modules available for the Web version.

**Comment by DavidDelco** [comment]
OK, it's clear! Thank you.
Sorry for using the bad topic "Issue"  :-(  in effect it was only a question!

**Comment by juacas** [comment]
You are welcome! You can use the users' forum at https://moodle.org/mod/forum/discuss.php?d=354875
