### ISSUE TITLE
Game not launching

### ISSUE THREAD

**Issue by vfremaux** [juacas/moodle-mod_treasurehunt#45]
when kicking the "Play" button, the game screen stiucks on ladong the game. 
Examinating the JS, after a long while comes this : 

Error: Mismatched anonymous define() module: function() {
var define,module,exports;return (function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
/* eslint-env node */
'use strict';

// SDP helpers.
var SDPUtils = {};

// Generate an alphanumeric identifier for cname or mids.
// TODO: use UUIDs instead? https://gist.github.com/jed/982883
SDPUtils.generateIdentifier = function() {
  return Math.random().toString(36).substr(2, 10);
};

// The RTCP CNAME used by all peerconnections from the same JS.
SDPUtils.localCName = SDPUtils.generateIdentifier();

// Splits SDP into…

We are using a M3.7 with a quite lot of plugins installed... this may come from interacitons, ..  or not. Behaviour changes wether JS caches are on or Off, 
Your opinion ?

**Comment by juacas** [comment]
I'm trying to reproduce it....
Does the problem ceases after a reload of the play page?

**Comment by juacas** [comment]
Hello, would you be so kind to test the version at develop branch (commit 83e28f4bb6bd07d5bfa55a818cd76605c8856333) from github 
I couldn't reproduce your error but I suspect that your problem may be related to an external library not encapsulated propertly.
This commit has been  tested in Moodle 3.7 without errors.
Regards.

**Comment by vfremaux** [comment]
Got last devel version for testing and made a bit of analysis.
Actually your plugin do replace the moodle stadnard jquery version (3.2.1) with your 2.4.1 for your internal compatibility for what i can understand.

I tried to remove the jquery 2.4.1 override to see what happens, Indeed the AMD require error is gone, but as could be expected there are other errors inside the tresorhunt implementation... 

I tried my side to remove useless modules or extra scripts, so cleaning out what is called from the php page. I got also lot of errors in an old Chrome, what i solved using a newer Chrome Canari version i had installed. (some parts of the implementation use recent array function syntaxes, and let instruction that are poorly supported by old chrome versions (< 49))

My opinion indeed is that the restrictions you need for running your JS integration probably is colliding with other AMD requirements... will be hard to check out indeed.

**Comment by juacas** [comment]
Does the play page works with jQuery 2 and the last changes?
Currently jQuery 2 is needed by jQuery mobile which is the framework of the
playing page.
If not, please post the errors shown in the console (without wiping out
jQuery 2).

We are working on a new implementation of the player, but it is still not
ready.

**Comment by vfremaux** [comment]
Here is the complete error track : target environemnet is FF 75.0 on Windows 8.0 Pro

Cette page utilise la propriété non standard « zoom ». Envisagez d’utiliser calc() dans les valeurs des propriétés pertinentes ou utilisez « transform » avec « transform-origin: 0 0 ». play.php
Successfully compiled asm.js code (total compilation time 1086ms) first.js
Error: Mismatched anonymous define() module: function() {
var define,module,exports;return (function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
/* eslint-env node */
'use strict';

// SDP helpers.
var SDPUtils = {};

// Generate an alphanumeric identifier for cname or mids.
// TODO: use UUIDs instead? https://gist.github.com/jed/982883
SDPUtils.generateIdentifier = function() {
  return Math.random().toString(36).substr(2, 10);
};

// The RTCP CNAME used by all peerconnections from the same JS.
SDPUtils.localCName = SDPUtils.generateIdentifier();

// Splits SDP into… require.js:168:17
Erreur dans les liens source : Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
URL de la ressource : https://demo.formation-enligne.com/lib/requirejs.php/-1/core/first.js
URL du lien source : bootstrap-select.min.js.map

I attach also the complete assembled page output, 

[treasurehunt_play.php.txt](https://github.com/juacas/moodle-mod_treasurehunt/files/4564593/treasurehunt_play.php.txt)

I can notice that our plugins are adding some js_pending modules and you had to override some for compatibility. Maybe our added js_pendings are adding such incompatibilities you had to face to.

Anyway, thanks for your attention, our target is public education in Bretagne, addressing 240.000 students in 240 secondary schools... ;-)

**Comment by juacas** [comment]
you are wellcome.
Please give a try to branch  /feature/bootstrap_play_page just to tell if the error is gone with this prototype player page.

**Comment by vfremaux** [comment]
bingo ! Error has gone away and playground is launching great. We'll have some translations to complete in french. At the bottom is a spanish text "Mostrar Pista" that might be internationalized.

By the way, is there any other solution that could keep the js caching on in some way ? here our first.js weights around 10Mo and needs around 24 seconds to assemble moodleside and transfer to the browser when not cached neither compressed. This is a bit lot for common users...

we can keep on actively reporting and collaborate testing and QA for you with our internal team. The plugin is greatly designed and should convince many Geography teachers :-)

**Comment by juacas** [comment]
Due to the current need to inject jquery2 in the player-page, the javascript cache break the page.
The url first.js usually weights <2MB and its hasn't been an issue until now.
Please be tuned to the changes I'm working on which will fix this problem... I hope.

**Comment by juacas** [comment]
Please give a try to the develop branch and upgrade your treasurehunt version.
You'll find new controls (in system settings and in treasurehunt settings) to control which style to use in the player-page.
"bootstrap player" does not use jquery mobile, it is very light-weight and may be the perfect fit for you.
