### ISSUE TITLE
Optimizing Backup & Restore

### ISSUE THREAD

**Issue by rschrenk** [juacas/moodle-mod_treasurehunt#49]
Hello,
we have a big Moodle site and recognized that Backup & Restore of all courses was getting slow. After making a little Profiling we found out, that the inclusion of GeoJS, that is loaded by mod_treasurehunt, made up 20% of all time.

![geojs](https://user-images.githubusercontent.com/8080807/99584181-e66b3500-29e4-11eb-8258-57015c877d95.png)

After checking your backup and restore stepslib I found out, that both include your locallib, which includes GeoJS causing it to run autoloading. As far as I could examine, there is no need to include locallib at all in your backup and restore stepslib.

Could you please check, if that is true, and remove the inclusion of locallib from those scripts?

Kind regards

**Comment by juacas** [comment]
Thank you for reporting this issue. I'll fix it as soon as possible.
Regards.

**Comment by juacas** [comment]
I've implemented your suggestion into v1.5.0 release. Thank you for contributing.
