### ISSUE TITLE
GDPR infringement

### ISSUE THREAD

**Issue by rschrenk** [juacas/moodle-mod_treasurehunt#51]
Hello,

we recognized, that mod_treasurehunt uses Google APIs in
- https://github.com/center-for-learning-management/eduvidual-src/blob/3e94b407304f36f8d9e1b0c5c5924d98f4112295/mod/treasurehunt/css/playerfancy/styles.css#L184
- https://github.com/center-for-learning-management/eduvidual-src/blob/3e94b407304f36f8d9e1b0c5c5924d98f4112295/mod/treasurehunt/styles.css#L184
- https://github.com/center-for-learning-management/eduvidual-src/blob/3e94b407304f36f8d9e1b0c5c5924d98f4112295/mod/treasurehunt/css/playerbootstrap/styles.css#L184

As for European sites, this causes an infringement of the GDPR. Would it be possible to fix that?

Kind regards

**Comment by juacas** [comment]
Of course, it is easy to fix because that style actually is not used and can be deleted. I'll do it.
However, please, can you elaborate the issue. Why is it an infringement of the GDPR? I'm interested in understanding it.
IMHO that URL just download a image and does not store cookies nor sends any personal data.

**Comment by rschrenk** [comment]
In January, a German court ruled that embedding fonts, CSS or JavaScript files from servers outside the EU alone is a violation of the GDPR.

https://dejure.org/dienste/vernetzung/rechtsprechung?Text=3%20O%2017493/20

The IP address of the user could allow an assignment to persons and would thus represent a personal data, which is then transmitted illegally.

**Comment by rschrenk** [comment]
Here is the decision of the court: 

https://openjur.de/u/2384915.html

Here is a translation usind deepl.com
 
> Tenor
> 
> (1) The defendant is ordered to refrain from disclosing the plaintiff's IP address by providing a font of the provider Google (Google Fonts) to the provider of this font when the plaintiff calls up a website operated by the defendant, upon notification of an administrative fine of up to €250,000.00 to be determined for each case of infringement, or, in the event of infringement, upon notification of an administrative fine of up to €250,000.00 to be determined for each case of infringement, or, in the event of infringement, upon notification of an administrative fine of up to six months to be determined for each case of infringement.
> 
> (2) The defendant is ordered to provide the plaintiff with information as to whether personal data relating to the plaintiff are being processed and, if so, to provide information as to which personal data relating to the plaintiff are being stored.
> 
> 3. the defendant is ordered to pay the plaintiff €100.00 plus interest thereon in the amount of 5 percentage points above the base interest rate since January 28, 2021.
> Reasons
> 
> The admissible action is quite predominantly well-founded.
> 
> I.
> 
> The plaintiff has a claim against the defendant for injunctive relief against the disclosure of the plaintiff's IP addresses to Google under § 823 (1) in conjunction with § 1004 BGB analogously. § 1004 BGB analogously.
> 
> The unauthorized disclosure of the plaintiff's dynamic IP address by the defendant to Google constitutes a violation of the general right of personality in the form of the right of informational self-determination under § 823 (1) BGB. The right to informational self-determination includes the right of the individual to determine the disclosure and use of his or her personal data.
> 
> (1) The dynamic IP address disclosed by the defendant to Google is a personal data within the meaning of Section 12 (1) and (2) of the German Telemedia Act (TMG) (in the version applicable at the time of transmission, hereinafter the old version), Section 3 (1) of the German Federal Data Protection Act (BDSG), Article 4 No. 1 of the German Data Protection Regulation (DS-GVO).
> 
> The dynamic IP address constitutes personal data for a website operator, because the website operator has legal means in the abstract that could reasonably be used to have the person concerned determined with the help of third parties, namely the competent authority and the Internet access provider, on the basis of the stored IP addresses (BGH, judgment of May 16, 2017 - VI ZR 135/13). It is sufficient for the defendant to have the abstract possibility of determining the persons behind the IP address. It does not matter whether the defendant or Google has the concrete possibility of linking the IP address to the plaintiff.
> 
> 2 The defendant violated the plaintiff's right to informational self-determination by forwarding the dynamic IP address to Google when the plaintiff accessed the defendant's website.
> 
> The automatic forwarding of the IP address by the defendant to Google was an inadmissible encroachment on the plaintiff's general right of personality under data protection law, since it is undisputed that the plaintiff did not consent to this encroachment pursuant to Section 13 (2) TMG a.F., Article 6 (1) a) DSGVO. 3.
> 
> There is also no justification for the encroachment on the general right of personality. There is no legitimate interest of the defendant within the meaning of Art. 6 (1) f) DS-GVO, as claimed by the defendant, because Google Fonts can also be used by the defendant without a connection to a Google server being established when the website is called up and a transmission of the IP address of the website users to Google taking place. 4.
> 
> 4 The plaintiff was also not required to encrypt his own IP address before calling up the defendant's website. To require this of the plaintiff would run counter to the purpose of the data protection law concerned here, which primarily aims to protect natural persons from impairment when processing their personal data, but would rather reverse this, as such an obligation would restrict the rights holder in exercising his rights worth protecting {LG Dresden, judgment of 11.01.2019, file number 1 AO 1582/18).
> 
> (5) The risk of repetition is to be affirmed. It is undisputed that the IP address of the plaintiff was forwarded to Google when the plaintiff visited the website of the defendant. Previous unlawful interference gives rise to a factual presumption of the risk of repetition, which has not been rebutted by the defendant. The risk of repetition is not eliminated by the fact that the defendant now uses Google Fonts in such a way that the IP address of the website visitors is no longer disclosed to Google. The risk of repetition can only be eliminated by a cease-and-desist declaration backed by a penalty.
> 
> II.
> 
> The plaintiff's right to information follows from Art. 15, Art. 4 No. 2 DS-GVO.
> 
> III.
> 
> The plaintiff is entitled to claim damages under Article 82 (1) of the GDPR. The concept of damage within the meaning of Article 82 of the GDPR is to be interpreted broadly in accordance with recital 146 p. 3, the term "damage" is to be interpreted broadly. The interpretation should fully comply with the objectives of this Regulation, including the objective of sanction and prevention (BeckOK Datenschutzrecht, Wolff/Bring, 38th Edition, DS-GVO Art. 82, para. 24). Sufficient is like. Art. 82 (1) GDPR, non-material damage is also sufficient. Whether a materiality threshold must be reached or exceeded and so-called trivial damages must be excluded is disputed (see BVerfG NJW 2021, 1005, para. 20 with further references; Kohn ZD 2019, 498 (501); Paal MMR 2020, 14 (16)), but can be left open in this case. The defendant admits that prior to the modification of its website, it transmitted the plaintiff's IP address to Google when he visited its website. The transmission of the IP address thus did not take place only once. In view of the plaintiff's loss of control over a personal data to Google, a company that is known to collect data about its users, and the individual discomfort felt by the plaintiff as a result, the associated encroachment on the general right of personality is so significant that a claim for damages is justified. It must also be taken into account that it is undisputed that the IP address was transmitted to a Google server in the USA, whereby an adequate level of data protection is not guaranteed there (see ECJ, judgment of July 16, 2020 - C-311/18 (Facebook Ireland u. Schrems), NJW 2020, 2613) and that the liability arising from Article 82 (1) of the GDPR is intended to prevent further infringements in a preventive manner and to create an incentive for security measures. The amount of damages claimed is appropriate in view of the severity and duration of the infringement and is not contested by the defendant.
> 
> 
> Translated with www.DeepL.com/Translator (free version)

**Comment by juacas** [comment]
OMG! In modern web apps there is a miriad of resources linked to servers that one never knows where they are!
This may be a nightmare. Nevertheless in this case the issue was easy to fix.
Thank you for your interest in the plugin and for reporting the issue.
Regards.

**Comment by llttugraz** [comment]
@juacas 
According to the GDPR, we as service provider have to inform our users about which personal data is transferred to which servers or leaves the Moodle Platform while they use this plugin. As @rschrenk has mentioned here, the IP address is also considered as personal data.

Examples are the street maps, and some JS libraries that you load from external servers / services. I would have to go through each line of code to discover which personal data goes where.

Do you have a complete list of personal data and the external services / servers where these data are transferred to?
IP, user's actual position, browser information or some user's data from Moodle DB?, etc...?

That would help us a lot. Thank you!

**Comment by juacas** [comment]
Hi @llttugraz, as long as I know, the only built-in connections to external services are map tiles (BingMaps AerialLayer and Open Street Map) and Open Street Map geocoder.
These will necessarily receive user's IP.

The rest of the communications are within Moodle server and client.
However, If you find any avoidable network activity, please let me know and I'll try to fix it.
