### ISSUE TITLE
Return from activity to treasurehunt

### ISSUE THREAD

**Issue by Avemaar** [juacas/moodle-mod_treasurehunt#52]
If the stages use not simple question but activity, would be great if the
user would returned to tresurehunt after complete the activity, thanks in advance

**Comment by juacas** [comment]
Sorry, but I think it is impossible because the other activities are not aware of the existance of Treasurehunt.
Once you go to other page the control of the navigation is fully controlled by Moodle.
However, it will be very wellcome if someone can contribute with such functionality
