### ISSUE TITLE
ensure filters are applied on student view

### ISSUE THREAD

**Issue by jpahullo** [juacas/moodle-mod_treasurehunt#55]
It seems that https://github.com/juacas/moodle-mod_treasurehunt/blob/923b7e1f328c85261c7bc9b161ac28e5f5e12ac9/locallib.php#L1792 prevents from applying installed filters when a student is visiting the activity. However, preview mode for teachers work ok.

**Comment by juacas** [comment]
Yes. It was a fix under development. It was stopped for a while. Nevertheless, I have released it today. Let me know if it works.
