### ISSUE TITLE
Duplicate line

### ISSUE THREAD

**Issue by xmontana** [juacas/moodle-mod_treasurehunt#57]
https://github.com/juacas/moodle-mod_treasurehunt/blob/f497befa9c7e43f76363cd09f5e506bcd88e2574/locallib.php#L1773

Hello @juacas !

The function line is duplicated, and cause a warning during upgrade/instalation.

Thank you for the grate work!

**Comment by jpahullo** [comment]
In version v1.5.4 it was solved, I think.

**Comment by juacas** [comment]
Sorry for such a bad commit. Too many things at the same time, I guess. ![bitmoji](https://sdk.bitmoji.com/render/panel/a1c09946-650d-4e6a-a498-12b74c0a824e-9535e943-fe69-4185-b704-37d2870d911d-v1.png?transparent=1&palette=1&width=86)
