### ISSUE TITLE
QR code not generating

### ISSUE THREAD

**Issue by idobraca** [juacas/moodle-mod_treasurehunt#61]
API to generate QR code chart.googleapis.com is no longer available. 
Solution is to change **https://chart.googleapis.com/chart?cht=qr&chs=500x500&chl=** with **https://quickchart.io/qr?size=500&text=** in **treasurehunt\amd\build\webqr.min.js** and **treasurehunt\amd\src\webqr.js**.

**Comment by juacas** [comment]
Thanks for reporting. Fix released as v1.5.7
